# Generated by Django 2.2.4 on 2019-09-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuesOfDistress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cues_id', models.CharField(default='', editable=False, max_length=50)),
                ('cues1', models.CharField(max_length=255)),
                ('cues2', models.CharField(max_length=255)),
                ('cues3', models.CharField(max_length=255)),
                ('cues4', models.CharField(max_length=255)),
                ('cues5', models.CharField(max_length=255)),
                ('cues6', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Date_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PersonCompleting', models.CharField(default='', editable=False, max_length=50)),
                ('Date', models.DateField(auto_now_add=True)),
                ('TimeIncidentStarted', models.DateTimeField(blank=True, null=True)),
                ('TimeIncedentEnded', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time_id', models.CharField(default='', editable=False, max_length=50)),
                ('wakingup', models.CharField(max_length=255)),
                ('pain', models.CharField(max_length=255)),
                ('staff', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_id', models.CharField(default='', editable=False, max_length=50)),
                ('reason1', models.CharField(max_length=255)),
                ('reason2', models.CharField(max_length=255)),
                ('reason3', models.CharField(max_length=255)),
                ('reason4', models.CharField(max_length=255)),
                ('reason5', models.CharField(max_length=255)),
            ],
        ),
    ]
