# Generated by Django 2.2.3 on 2019-09-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakingup', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(max_length=255)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbaform.Location')),
            ],
        ),
    ]
