# Generated by Django 2.2.4 on 2019-09-16 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbaform', '0002_auto_20190917_0106'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CuesOfDistress',
        ),
        migrations.DeleteModel(
            name='Triggers',
        ),
        migrations.RemoveField(
            model_name='location',
            name='pain',
        ),
        migrations.RemoveField(
            model_name='location',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='location',
            name='staff',
        ),
    ]
