# Generated by Django 2.2.4 on 2019-09-18 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbaform', '0003_auto_20190917_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason1', models.CharField(max_length=255)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fbaform.Location')),
            ],
        ),
    ]
