# Generated by Django 2.2.5 on 2019-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbaform', '0003_auto_20190923_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anticident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anticident', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
