# Generated by Django 2.2.4 on 2020-02-01 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fba',
            name='intensity',
            field=models.PositiveSmallIntegerField(
                choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5')],
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
