# Generated by Django 2.2.4 on 2020-01-13 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_fba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fba',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fba', to=settings.AUTH_USER_MODEL),
        ),
    ]
