# Generated by Django 2.2.4 on 2020-02-01 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_fba', '0002_auto_20200202_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fba',
            name='intensity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
