# Generated by Django 2.2.4 on 2020-01-29 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_merge_20200118_1613'),
        ('form_fba', '0002_auto_20200113_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fba',
            name='user',
        ),
        migrations.AddField(
            model_name='fba',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fba', to='users.Post'),
        ),
        migrations.AlterField(
            model_name='fba',
            name='intensity',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
