# Generated by Django 2.2.4 on 2020-01-29 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_fba', '0003_auto_20200129_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fba',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Post'),
        ),
    ]
