# Generated by Django 2.2.4 on 2020-02-02 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('form_fba', '0003_auto_20200202_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='fba',
            name='client_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Post'),
        ),
        migrations.AddField(
            model_name='fba',
            name='timestamp',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='fba',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
