# Generated by Django 2.2.4 on 2020-02-02 02:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0004_auto_20200202_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fba',
            name='timestamp',
        ),
    ]
