# Generated by Django 2.2.4 on 2020-02-04 02:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0009_auto_20200203_1404'),
        ('form_fba', '0006_auto_20200203_1253'),
    ]

    operations = [
    ]
