# Generated by Django 2.2.4 on 2020-02-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_fba', '0010_merge_20200204_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='br',
            name='sum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
