# Generated by Django 2.2.4 on 2020-02-05 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0011_br_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='br',
            name='sum',
        ),
    ]
