# Generated by Django 2.2.3 on 2020-02-05 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form_fba', '0011_br_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='fba',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
