# Generated by Django 2.2.3 on 2020-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0012_fba_date_created'),
        ('form_fba', '0012_remove_br_sum'),
    ]

    operations = [
    ]
