# Generated by Django 2.2.3 on 2020-02-05 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('form_fba', '0013_merge_20200205_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fba',
            name='date_created',
        ),
    ]
