# Generated by Django 2.2.3 on 2019-11-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterUsers',
        ),
    ]
