# Generated by Django 2.2.3 on 2019-11-29 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191129_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gender',
        ),
    ]
