# Generated by Django 2.2.3 on 2019-11-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_post_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
