# Generated by Django 2.2.3 on 2019-12-01 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='client_name',
        ),
    ]
