# Generated by Django 2.2.3 on 2019-12-01 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191201_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_details',
            new_name='date_issued',
        ),
    ]
