# Generated by Django 2.2.3 on 2019-12-05 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191201_1033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Support_worker',
        ),
    ]
