# Generated by Django 2.2.3 on 2019-12-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191206_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='client2_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
