# Generated by Django 2.2.3 on 2019-12-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_post_client2_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='client2_name',
        ),
    ]
