# Generated by Django 2.2.3 on 2019-12-06 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_post_client2_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Support_worker',
            new_name='author',
        ),
    ]
