# Generated by Django 2.2.3 on 2019-12-19 07:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191206_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='DOB',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 12, 19, 7, 15, 0, 686060, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
