# Generated by Django 2.2.3 on 2020-01-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200107_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='00', max_length=2),
        ),
    ]
