# Generated by Django 2.2.3 on 2020-01-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_post_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='00', editable='false', max_length=2),
        ),
    ]
