# Generated by Django 2.2.4 on 2020-01-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200107_1145'),
        ('users', '0014_auto_20200107_1251'),
    ]

    operations = [
    ]
